project:
  type: book

book:
  title: "Minimal Computing 101"
  author: 
    - name: Gimena del Rio Riande
      orcid: 0000-0002-8997-5415
  
    - name: Gabriel Alejandro Calarco
      orcid: 0000-0002-7841-6538

    - name: Joanna Crow
      orcid: 0000-0003-2588-0115
    

    - name: Roy Youdale 
      orcid: 0000-0001-5819-4774

  date: "8/8/2025"
  # cover-image: cover.jpg
  chapters:
    - index.qmd
    - sobre_minimalcomputing.qmd
    - about_minimalcomputing.qmd
    - references.qmd
    - proyecto.qmd

bibliography: references.bib

format:
  html:
    theme:
      #- cosmo
      # - brand
      simplex
  pdf:
    documentclass: scrreprt



